login screen changes
Ganesh-softsuave/Affitu pull request #28
Opened 2023-11-06 14:39 UTC by firnas16

![simulator_screenshot_5BC41752-6740-4567-A019-72B3A1BF2DE2](https://github.com/Ganesh-softsuave/Affitu/assets/94963741/c68b91ff-9569-491f-8851-614501bd8f0c)

2023-11-07 10:09 UTC, Ganesh-softsuave requested changes

2023-11-07 10:09 UTC, Ganesh-softsuave commented on lib/translation/resources/en.ts
> +  lets_Get_Started: 'Let’s get started!',
Please use key as lower case

2023-11-07 10:09 UTC, Ganesh-softsuave commented on src/screens/Login/index.tsx
> +  console.log('sssaa>>>');
Please remove logs

2023-11-07 10:09 UTC, Ganesh-softsuave commented on src/screens/Login/index.tsx
> +import {useTranslation} from 'react-i18next';
Please use import statement orderwise

2023-11-07 10:09 UTC, Ganesh-softsuave commented on src/screens/Login/index.tsx
> +        name={'phoneNumber'}
Please create Separate component for Phone number text input

2023-11-07 10:09 UTC, Ganesh-softsuave commented on src/screens/Login/ViewModal.ts
> +  function handleNumberChange(input: string) {
Please move all this logic to Phonenumber component

2023-11-07 10:09 UTC, Ganesh-softsuave commented on src/screens/Login/styles.tsx
> +      right: 80,
Please use pixelSizeHorizontal for all over the component

2023-11-08 06:04 UTC, BhavaniMM commented on src/screens/Home/index.tsx
> +import Login from '../Login';
please import absolute path

2023-11-09 14:50 UTC, Ganesh-softsuave approved these changes

2023-11-09 14:56 UTC, dilipkrishna97 approved these changes

2023-11-09 14:56 UTC, merged