Sign up screen changes
Ganesh-softsuave/Affitu pull request #29
Opened 2023-11-06 15:39 UTC by dilipkrishna97

2023-11-07 13:49 UTC, Ganesh-softsuave requested changes

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/CharactersCount.tsx
> +import CustomText from '../CustomTextField/CustomTextField';
use absolute path

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/LeftIcon.tsx
> +import CustomIcon from '../CustomIcon';
use absolute path

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/LeftIcon.tsx
> +        <CustomIcon name={leftIcon} size={12} />
use fontPixel for font size

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/RightIcon.tsx
> +        <CustomIcon name={rightIcon} size={12} />
use fontPixel for size

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/RightIcon.tsx
> +import CustomIcon from '../CustomIcon';
use absolute path

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/index.tsx
> +import {useThemeContext} from '@src/context/themeContext';
please import statement properly

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/index.tsx
> +                placeholderTextColor={'#C4C5D6'}
Please use color from context

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/components/CustomInput/styles.ts
> +      color: 'red',
Please use color from context

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/BottomSection.tsx
> +function BottomSection({control}: BottomSectionProps): JSX.Element {
change the name to Privacy&Terms

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/BottomSection.tsx
> +          validate: value => value === true,
use useMemo

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/ViewModal.ts
> +  function handleOnContinue(data: any): SubmitHandler<FormValues> {
change function name to onSubmit

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/index.tsx
> +        onPress={() => navigate.goBack()}
please move it to viewModel

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/index.tsx
> +        <CustomIcon name="arrow-back" size={12} />
use fontPixel for all size

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/index.tsx
> +        {translate('Create your Account')}
Please check this is coming from translation text

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/index.tsx
> +          ...confirmPasswordRules,
Please use useMemo

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/index.tsx
> +          ...phoneNumRules,
use useMemo

2023-11-07 13:49 UTC, Ganesh-softsuave commented on src/utils/FormUtils.ts
> +  required: 'Full name is required',
use translation

2023-11-07 14:35 UTC, dilipkrishna97 commented on src/utils/FormUtils.ts
> +  required: 'Full name is required',
As this is an constant file we can't use the hook inside this file.

2023-11-08 05:27 UTC, BhavaniMM commented on lib/translation/resources/en.ts
> +  phone_number: 'phone_number',
Is phone_number value correct?

2023-11-08 05:27 UTC, BhavaniMM commented on lib/translation/resources/en.ts
> +  hide_password: 'hide_password',
Please check hide_confirm_password and hide_password values

2023-11-08 05:31 UTC, BhavaniMM commented on src/Navigator/MainNavigator/index.tsx
> +import AuthNavigator from '../AuthNavigator';
please import the absolute path

2023-11-08 05:36 UTC, BhavaniMM commented on src/components/CheckBox/styles.ts
> +      height: pixelSizeVertical(12),
Please use widthPixel and heightPixel utility methods for height and widths

2023-11-08 05:41 UTC, BhavaniMM commented on src/components/CustomInput/CharactersCount.tsx
> +import {StyleSheet, View} from 'react-native';
Please maintain the import order for React, React Native libraries, and project files

2023-11-08 05:43 UTC, BhavaniMM commented on src/components/CustomInput/CharactersCount.tsx
> +      style={StyleSheet.compose(styles.textCountContainer, {
Please use styleSheetCompose utility method instead of using StyleSheet compose

2023-11-08 05:44 UTC, BhavaniMM commented on src/components/CustomInput/LeftIcon.tsx
> +import {TouchableOpacity} from 'react-native';
Please maintain the import order for React, React Native libraries, and project files

2023-11-08 05:45 UTC, BhavaniMM commented on src/components/CustomInput/RightIcon.tsx
> +import {TouchableOpacity} from 'react-native';
Please maintain the import order for React, React Native libraries, and project files

2023-11-08 05:47 UTC, BhavaniMM commented on src/components/CustomInput/index.tsx
> +          <View style={StyleSheet.compose(styles.container, containerStyles)}>
Please use styleSheetCompose utility method instead of using StyleSheet compose in all places in this file

2023-11-08 05:49 UTC, BhavaniMM commented on src/components/CustomInput/index.tsx
> +              <LeftIcon
please add testid for this icon

2023-11-08 05:50 UTC, BhavaniMM commented on src/components/CustomInput/index.tsx
> +              <RightIcon
please add testid for this icon

2023-11-08 05:50 UTC, BhavaniMM commented on src/components/CustomInput/styles.ts
> +import {StyleSheet} from 'react-native';
Please maintain the import order for React, React Native libraries, and project files

2023-11-08 05:51 UTC, BhavaniMM commented on src/components/CustomInput/styles.ts
> +      width: pixelSizeHorizontal(30),
Please use widthPixel and heightPixel utility methods for height and widths in all places in this file

2023-11-08 05:57 UTC, BhavaniMM commented on src/screens/AuthScreens/SignUp/index.tsx
> +  const styles = style(themeContext.color);
please add styles type

2023-11-08 05:57 UTC, BhavaniMM commented on src/screens/AuthScreens/SignUp/index.tsx
> +      <TouchableOpacity onPress={onBack} style={styles.backArrowContainer}>
please add testId

2023-11-08 06:00 UTC, BhavaniMM commented on src/screens/Home/index.tsx
> +import {useNavigation} from '@react-navigation/native';
please maintain the import order. check this in all files

2023-11-08 06:01 UTC, BhavaniMM commented on src/screens/Home/index.tsx
> +      <Text onPress={() => navigate.navigate(ScreenName.SIGN_UP_SCREEN)}>
Please add this functionality in viewmodel

2023-11-08 06:22 UTC, BhavaniMM commented on src/HOC/WithLogoBackGround/index.tsx
> +const BackGroundImageStyles = StyleSheet.create<StyleSheetType>({
please create separate style file

2023-11-08 06:29 UTC, dilipkrishna97 commented on src/components/CustomInput/index.tsx
> +              <LeftIcon
I have added the testId inside the Left icon component

2023-11-08 06:29 UTC, dilipkrishna97 commented on src/components/CustomInput/index.tsx
> +              <RightIcon
I have added the testId inside the Right icon component

2023-11-08 06:34 UTC, dilipkrishna97 commented on src/screens/Home/index.tsx
> +      <Text onPress={() => navigate.navigate(ScreenName.SIGN_UP_SCREEN)}>
This changes are for testing purpose only

2023-11-08 06:54 UTC, BhavaniMM commented on src/screens/AuthScreens/SignUp/index.tsx
> +    <ScrollView style={styles.mainContainer}>
Please add withSafeAreaView HOC

2023-11-08 06:57 UTC, dilipkrishna97 commented on src/screens/AuthScreens/SignUp/index.tsx
> +          ...confirmPasswordRules,
As I have explained it is not possible to move the rules to view modal using useMemo

2023-11-08 07:21 UTC, BhavaniMM commented on src/screens/AuthScreens/SignUp/PrivacyAndTerms.tsx
> +        name={translate('check_box_title')}
check_box_title this key is not there in en file. please check

2023-11-08 07:55 UTC, dilipkrishna97 commented on src/screens/AuthScreens/SignUp/index.tsx
> +    <ScrollView style={styles.mainContainer}>
I have wrapped the component while exporting

2023-11-08 10:52 UTC, Ganesh-softsuave submitted a review, later dismissed

2023-11-08 10:52 UTC, Ganesh-softsuave commented on src/components/CustomInput/CharactersCount.tsx
> +      {showCharacterCount && !!maxLength && (
Please use boolean of or !! operator wrap

2023-11-08 10:52 UTC, Ganesh-softsuave commented on src/screens/AuthScreens/SignUp/styles.ts
> +      fontSize: 18,
use fontPixel

2023-11-08 12:11 UTC, Ganesh-softsuave approved these changes

2023-11-08 12:11 UTC, merged