Feature/ Implemented Add property home screen
Ganesh-softsuave/Affitu pull request #30
Opened 2023-11-07 09:03 UTC by BhavaniMM

Description:
Implemented Add property home screen

Testing:
IOS:
![Screenshot 2023-11-07 at 2 24 38 PM](https://github.com/Ganesh-softsuave/Affitu/assets/135315139/7c270de6-e9ac-4f2e-9e5c-c9ff3687cc71)

Android:
![Screenshot 2023-11-07 at 2 24 22 PM](https://github.com/Ganesh-softsuave/Affitu/assets/135315139/3be437b4-1e2f-4b9b-9f02-fb829361b4db)

2023-11-07 10:00 UTC, Ganesh-softsuave commented
@BhavaniMM  Please check why font family not applying

2023-11-07 10:01 UTC, Ganesh-softsuave commented on src/screens/AddProperty/index.tsx
> +        <Image
Please create separate component for User Information

2023-11-07 10:04 UTC, Ganesh-softsuave commented on src/screens/AddProperty/index.tsx
> +      <Image
Please use flex direction row for this Content. avoid using position absolute here

2023-11-07 13:29 UTC, Ganesh-softsuave requested changes

2023-11-07 13:29 UTC, Ganesh-softsuave commented on src/components/UserInfo/index.tsx
> +import CustomText from '../CustomTextField/CustomTextField';
please import absolute path

2023-11-07 13:29 UTC, Ganesh-softsuave commented on src/screens/AddProperty/index.tsx
>        {/* the below view to be removed after adding header */}
Please remove the commented line

2023-11-07 13:29 UTC, Ganesh-softsuave commented on src/screens/AddProperty/index.tsx
> +          onPress={() => {}}
Please create one function in viewmodel  comment over the function

2023-11-08 06:06 UTC, BhavaniMM commented
> @BhavaniMM Please check why font family not applying

2023-11-08 13:01 UTC, Ganesh-softsuave requested changes

2023-11-08 13:01 UTC, Ganesh-softsuave commented on src/Navigator/MainNavigator/Constant.ts
> +  {key: 2, name: ScreenNameConstant.ADD_PROPERTY, Component: AddProperty},
Please create one more navigator in the name Owner Navigator as same as Auth Navigator move all  your  screens inside  that

2023-11-08 13:01 UTC, Ganesh-softsuave commented on src/Navigator/MainNavigator/ScreenNameConstant.ts
> +  ADD_PROPERTY: 'AddProperty',
move your screens to Owner navigator

2023-11-08 13:06 UTC, BhavaniMM commented on src/screens/AddProperty/ViewModel.ts
> +export default function ViewModel(): ViewModelReturnType {
It is mentioned as ViewModelReturnType

2023-11-08 13:58 UTC, Ganesh-softsuave approved these changes

2023-11-08 13:58 UTC, Ganesh-softsuave commented on src/Navigator/OwnerNavigator/Constant.ts
> +  {key: 2, name: ScreenNameConstant.ADD_PROPERTY, Component: AddProperty},
Please change key as 1

2023-11-08 14:07 UTC, Ganesh-softsuave approved these changes

2023-11-08 14:07 UTC, merged